In [1]:
import pandas as pd

In [2]:
genes = pd.read_parquet("data/processed/genes.parquet")

genes.head()

,orgId,locusId,sysName,scaffoldId,begin,end,gene_length,type,strand,gene,desc,GC,n_total_experiments,n_confident_experiments,frac_not_confident,mean_fit_confident,frac_essential_all,frac_essential_confident,essentiality_class
0,ANA3,7022496,Shewana3_4141,248373,1030,1248,219,1,+,,putative transposase (RefSeq),0.4429,107,11,0.897196,0.202190,0.000000,0.000000,non_essential
1,ANA3,7022497,Shewana3_4142,248373,1491,2471,981,1,-,,IS4 family transposase (RefSeq),0.4760,107,14,0.869159,-0.091833,0.000000,0.000000,non_essential
2,ANA3,7022498,Shewana3_4143,248373,2555,2836,282,1,-,,hypothetical protein (RefSeq),0.4504,0,0,NaN,NaN,NaN,NaN,no_data
3,ANA3,7022499,Shewana3_4144,248373,2880,3239,360,1,-,,plastocyanin domain-containing protein (RefSeq),0.4278,107,35,0.672897,-1.013650,0.429907,0.685714,conditional
4,ANA3,7022500,Shewana3_4145,248373,3276,5612,2337,1,-,,copper-translocating P-type ATPase (RefSeq),0.4835,107,22,0.794393,-0.065183,0.000000,0.000000,non_essential

In [3]:
for col in genes.columns:
    print(col)

print("Number of genes:", len(genes))

orgId
locusId
sysName
scaffoldId
begin
end
gene_length
type
strand
gene
desc
GC
n_total_experiments
n_confident_experiments
frac_not_confident
mean_fit_confident
frac_essential_all
frac_essential_confident
essentiality_class
Number of genes: 221005

In [4]:
exps = pd.read_parquet("data/processed/experiments.parquet")

exps.head()

,orgId,expName,expDesc,expGroup,mutantLibrary,media,mediaStrength,condition_1,concentration_1,units_1,...,units_3,temperature,pH,aerobic,vessel,liquid,shaking,cor12,maxFit,nGenerations
0,ANA3,set1H1,L-Asparagine (N),nitrogen source,ANA3_ML1,ShewMM_noNitrogen,1.0,L-Asparagine,20,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.325698,4.241165,4.906891
1,ANA3,set1H10,L-Arginine (N),nitrogen source,ANA3_ML1,ShewMM_noNitrogen,1.0,L-Arginine,10,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.336924,2.913553,4.255501
2,ANA3,set1H13,L-Alanine (C),carbon source,ANA3_ML1,ShewMM_noCarbon,1.0,L-Alanine,20,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.369109,5.535615,NaN
3,ANA3,set1H15,L-Threonine (C),carbon source,ANA3_ML1,ShewMM_noCarbon,1.0,L-Threonine,20,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.297277,8.823762,4.587965
4,ANA3,set1H16,L-Serine (C),carbon source,ANA3_ML1,ShewMM_noCarbon,1.0,L-Serine,20,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.274661,15.069591,4.040016

In [22]:
print(len(exps["condition_1"].unique()))
print("Number of experiments:", len(exps))

351
Number of experiments: 7552

In [24]:
exps['media'].unique()

array(['ShewMM_noNitrogen', 'ShewMM_noCarbon', 'LB', 'ShewMM',
       'RCH2_defined_noCarbon', 'RCH2_defined_Glucose_noNitrogen',
       'RCH2_defined_glucose', 'RCH2_defined_glucose_noVitamin',
       'Varel_Bryant_medium_Glucose', 'BHIS', 'Varel_Bryant_medium', '',
       'Varel_Bryant_medium_noNitrogen', 'M2_noCarbon', 'M2_noNitrogen',
       'PYE', 'marine_broth_2216', 'DinoMM_noCarbon_HighNutrient',
       'DinoMM_noNitrogen_HighNutrient_GlucoseC', 'R2A',
       'RCH2_defined_noNitrogen', 'M9+sucrose', 'M9+starch',
       'M9+polygalacturonate', 'M9 minimal media_noCarbon',
       'Potato Dextrose Broth', 'Potato tuber', 'Potato stem',
       'DinoMM_noNitrogen_HighNutrient', 'DinoMM_noCarbon', 'MoYLS4',
       'MoLS4', 'MoLS4_no_Pyridoxine', 'MoLS4_no_Pantothenic_acid',
       'MoLS4_no_B12', 'MoLS4_no_Folic_acid', 'MoLS4_no_vitamins',
       'MoLS4_no_ammonium', 'MoLS4_no_Choline_chloride', 'Dv_base_medium',
       'Dv_base_Y_medium', 'LS4D', 'MoLS4_no_Mo_no_W', 'MoLS4_no_W',
       'MoLS4_no_Mo', 'MoLS4_no_sulfide', 'Dv_base_medium_no_Mo_no_W',
       'Dv_base_medium_no_W', 'Dv_base_medium_no_Mo', 'MoLS4_no_Biotin',
       'MoLS4_no_lipoic_acid', 'MoLS4_no_thiamine',
       'MoLS4_no_nicotinic_acid', 'MoLS4_no_ammonium_no_Mo_no_W',
       'MoLS4_no_ammonium_no_W', 'MoYLS4_no_iron',
       'MoLS4_no_ammonium_no_Mo', 'MOPS Rich Defined media_noCarbon',
       'M9 minimal media_noNitrogen', 'MOPS minimal media_noCarbon',
       'M63_no_sulfur', 'RCH2_defined_noCarbon_noVitamins',
       'ShewMM_MES_buffer', 'RCH2_defined', 'MG minimal media_noIron',
       'MG minimal media', 'MG minimal media_noCarbon',
       'DinoMM_alphaKetoGlutAcid_NoNitrogen',
       'DinoMM_L_lactateCarbon_HighNutrient',
       'DinoMM_L_lactateCarbon_HighNutrient_noVitamin', 'Mc_defined_H2',
       'McCas_formate_complete', 'Mc_defined_formate',
       'McCas_H2_complete', 'McCas_Formate_complete', 'McCas_MOPS',
       'McCas', 'McAA_formate_No_biotin', 'McAA_formate_No_FolicAcid',
       'McAA_formate_No_Pyroxidine', 'McAA_formate_No_Thiamine',
       'McAA_formate_No_Riboflavin', 'McAA_formate_No_NicotinicAcid',
       'McAA_formate_No_CaPantothenate', 'McAA_formate_No_B12',
       'McAA_formate_No_pABA', 'McAA_formate_No_lipolicAcid',
       'McAA_formate', 'Mc_H2_N_Free', 'Mc_formate_N_Free',
       'McCas_H2_Fe_Free', 'McCas_formate_Fe_Free', 'Mc_formate',
       'McCas_H2_No_Na2S', 'MoLS4_no_lactate', 'MoLS4_no_ammonia',
       'ALP_rich', 'ALP_defined_noC', 'ALP_richB',
       'DinoMM_noNitrogen_HighNutrient_SucroseC',
       'MOPS minimal media_Glucose_noNitrogen', 'M9_1percentGlucose',
       'CPG', 'M63_quarter_strength', 'BG11', 'BG11_noNitrogen', 'KB',
       'RCH2_Lactate_Nitrate_YE', 'RCH2_Lactate_1_M_Fe-Cu',
       'RCH2_Lactate_YE_1_M_Fe-Cu', 'RCH2_defined_no_vitamin',
       'RCH2_defined_glucose_MES', 'RCH2_defined_glucose_TAPS'],
      dtype=object)

In [7]:
fitness = pd.read_parquet("data/processed/fitness.parquet")

fitness.head()

  orgId  locusId  expName       fit         t
0  ANA3  7022496   set1H1 -0.251814 -0.398131
1  ANA3  7022496  set1H10 -0.109678 -0.198421
2  ANA3  7022496  set1H13  0.275650  0.582537
3  ANA3  7022496  set1H15  0.222707  0.280823
4  ANA3  7022496  set1H16  0.236262  0.455999

In [8]:
for col in fitness.columns:
    print(col)

print("Number of fitnesses:", len(fitness))

orgId
locusId
expName
fit
t
Number of fitnesses: 27410721

***

In [9]:
mvp_genes = pd.read_parquet("data/mvp/genes.parquet")

mvp_genes.head()

,orgId,locusId,sysName,scaffoldId,begin,end,gene_length,type,strand,gene,desc,GC,n_total_experiments,n_confident_experiments,frac_not_confident,mean_fit_confident,frac_essential_all,frac_essential_confident,essentiality_class
0,ANA3,7022496,Shewana3_4141,248373,1030,1248,219,1,+,,putative transposase (RefSeq),0.4429,95,11,0.884211,0.202190,0.0,0.00000,non_essential
1,ANA3,7022497,Shewana3_4142,248373,1491,2471,981,1,-,,IS4 family transposase (RefSeq),0.4760,95,12,0.873684,-0.144878,0.0,0.00000,non_essential
2,ANA3,7022498,Shewana3_4143,248373,2555,2836,282,1,-,,hypothetical protein (RefSeq),0.4504,0,0,NaN,NaN,NaN,NaN,no_data
3,ANA3,7022499,Shewana3_4144,248373,2880,3239,360,1,-,,plastocyanin domain-containing protein (RefSeq),0.4278,95,27,0.715789,-0.752290,0.4,0.62963,conditional
4,ANA3,7022500,Shewana3_4145,248373,3276,5612,2337,1,-,,copper-translocating P-type ATPase (RefSeq),0.4835,95,18,0.810526,-0.031323,0.0,0.00000,non_essential

In [10]:
unique_orgs = mvp_genes['orgId'].unique()
for org in unique_orgs:
    print(mvp_genes.loc[mvp_genes['orgId'] == org, ['orgId', 'begin', 'end', 'gene_length']].head(2))
    print()

  orgId  begin   end  gene_length
0  ANA3   1030  1248          219
1  ANA3   1491  2471          981

      orgId  begin  end  gene_length
4360  BFirm    270  479          210
4361  BFirm    663  947          285

         orgId  begin   end  gene_length
11542  Burk376      1   705          705
11543  Burk376   1073  1918          846

         orgId  begin   end  gene_length
18097  Cup4G11    607  2394         1788
18098  Cup4G11   2872  3996         1125

         orgId  begin   end  gene_length
25455  Dda3937     32   475          444
25456  Dda3937    567  1031          465

          orgId  begin   end  gene_length
29668  Ddia6719   1325  2425         1101
29669  Ddia6719   2591  3676         1086

          orgId  begin   end  gene_length
33778  DdiaME23   1325  2425         1101
33779  DdiaME23   2591  3676         1086

          orgId  begin   end  gene_length
37960  Dyella79      2  1192         1191
37961  Dyella79   1648  1959          312

         orgId  begin   end  gene_length
42277  HerbieS      1  1398         1398
42278  HerbieS   2012  3118         1107

      orgId  begin   end  gene_length
46992  Keio    190   255           66
46993  Keio    337  2799         2463

       orgId  begin   end  gene_length
51138  Korea    277  2127         1851
51139  Korea   2146  2391          246

      orgId  begin   end  gene_length
55287  Koxy      1  2415         2415
55288  Koxy   2444  3517         1074

      orgId  begin   end  gene_length
60596   MR1    334   774          441
60597   MR1    954  2504         1551

      orgId  begin   end  gene_length
65063   PV4    111  1490         1380
65064   PV4   1511  2611         1101

         orgId  begin   end  gene_length
68922  Pedo557      1  1431         1431
68923  Pedo557   1565  2113          549

        orgId  begin   end  gene_length
73886  Putida    147  1019          873
73887  Putida   1029  1820          792

      orgId  begin   end  gene_length
79449  SB2B     70   510          441
79450  SB2B    657  1571          915

       orgId  begin   end  gene_length
83094  Smeli   1353  4457         3105
83095  Smeli   4454  5446          993

        orgId  begin   end  gene_length
89311  WCS417    225  1742         1518
89312  WCS417   1781  2884         1104

                 orgId  begin   end  gene_length
94817  acidovorax_3H11    252  2318         2067
94818  acidovorax_3H11   2439  2660          222

        orgId  begin   end  gene_length
99781  azobra    795  2192         1398
99782  azobra   2463  3419          957

         orgId  begin  end  gene_length
105269  psRCH2     65  352          288
105270  psRCH2    303  632          330

                     orgId  begin   end  gene_length
109534  pseudo13_GW456_L13   5846  7339         1494
109535  pseudo13_GW456_L13   7517  8866         1350

               orgId  begin   end  gene_length
114686  pseudo1_N1B4   1060  1620          561
114687  pseudo1_N1B4   1719  2390          672

               orgId  begin   end  gene_length
120658  pseudo3_N2E3    379  1038          660
120659  pseudo3_N2E3   1076  2173         1098

                 orgId  begin   end  gene_length
126424  pseudo5_N2C3_1    463  1560         1098
126425  pseudo5_N2C3_1   1618  2451          834

               orgId  begin   end  gene_length
132424  pseudo6_N2E2     90   860          771
132425  pseudo6_N2E2   1006  1740          735

In [11]:
for col in mvp_genes.columns:
    print(col)

print("Number of genes:", len(genes))
print("Number of MVP genes:", len(mvp_genes))

orgId
locusId
sysName
scaffoldId
begin
end
gene_length
type
strand
gene
desc
GC
n_total_experiments
n_confident_experiments
frac_not_confident
mean_fit_confident
frac_essential_all
frac_essential_confident
essentiality_class
Number of genes: 221005
Number of MVP genes: 138518

In [12]:
mvp_exps = pd.read_parquet("data/mvp/experiments.parquet")

mvp_exps.head()

,orgId,expName,expDesc,expGroup,mutantLibrary,media,mediaStrength,condition_1,concentration_1,units_1,...,units_3,temperature,pH,aerobic,vessel,liquid,shaking,cor12,maxFit,nGenerations
0,ANA3,set1H1,L-Asparagine (N),nitrogen source,ANA3_ML1,ShewMM_noNitrogen,1.0,L-Asparagine,20,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.325698,4.241165,4.906891
1,ANA3,set1H10,L-Arginine (N),nitrogen source,ANA3_ML1,ShewMM_noNitrogen,1.0,L-Arginine,10,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.336924,2.913553,4.255501
2,ANA3,set1H13,L-Alanine (C),carbon source,ANA3_ML1,ShewMM_noCarbon,1.0,L-Alanine,20,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.369109,5.535615,NaN
3,ANA3,set1H15,L-Threonine (C),carbon source,ANA3_ML1,ShewMM_noCarbon,1.0,L-Threonine,20,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.297277,8.823762,4.587965
4,ANA3,set1H16,L-Serine (C),carbon source,ANA3_ML1,ShewMM_noCarbon,1.0,L-Serine,20,mM,...,,30,7,Aerobic,tube,Liquid,200 rpm,0.274661,15.069591,4.040016

In [13]:
for col in mvp_exps.columns:
    print(col)

print("Number of experiments:", len(exps))
print("Number of mvp experiments:", len(mvp_exps))

orgId
expName
expDesc
expGroup
mutantLibrary
media
mediaStrength
condition_1
concentration_1
units_1
condition_2
concentration_2
units_2
condition_3
concentration_3
units_3
temperature
pH
aerobic
vessel
liquid
shaking
cor12
maxFit
nGenerations
Number of experiments: 7552
Number of mvp experiments: 2164

In [14]:
unique_media = mvp_exps['media'].unique()
for media in unique_media:
    print(media)
    print(len(mvp_exps[mvp_exps['media'] == media]))
    print()

ShewMM_noNitrogen
81

ShewMM_noCarbon
157

LB
713

ShewMM
17

RCH2_defined_noCarbon
539

RCH2_defined_noNitrogen
83

R2A
82

M9+sucrose
6

M9+starch
4

M9+polygalacturonate
6

M9 minimal media_noCarbon
72

RCH2_defined_Glucose_noNitrogen
161

RCH2_defined_glucose_noVitamin
4

M9 minimal media_noNitrogen
32

MOPS minimal media_noCarbon
47

M63_no_sulfur
4

RCH2_defined_noCarbon_noVitamins
12

ShewMM_MES_buffer
2

RCH2_defined
1

MOPS minimal media_Glucose_noNitrogen
34

M9_1percentGlucose
1

RCH2_defined_glucose
23

RCH2_Lactate_Nitrate_YE
15

RCH2_Lactate_1_M_Fe-Cu
12

RCH2_Lactate_YE_1_M_Fe-Cu
6

RCH2_defined_no_vitamin
36

RCH2_defined_glucose_MES
5

RCH2_defined_glucose_TAPS
9

In [15]:
mvp_exps[mvp_exps['media'] == "Potato tuber"].head()

Empty DataFrame
Columns: [orgId, expName, expDesc, expGroup, mutantLibrary, media, mediaStrength, condition_1, concentration_1, units_1, condition_2, concentration_2, units_2, condition_3, concentration_3, units_3, temperature, pH, aerobic, vessel, liquid, shaking, cor12, maxFit, nGenerations]
Index: []

[0 rows x 25 columns]

In [16]:
plants = mvp_exps[mvp_exps['expGroup'] == 'plant']
print(plants['media'].unique())

[]

In [17]:
mvp_fitness = pd.read_parquet("data/mvp/fitness.parquet")

mvp_fitness.head()

  orgId  locusId  expName       fit         t
0  ANA3  7022496   set1H1 -0.251814 -0.398131
1  ANA3  7022496  set1H10 -0.109678 -0.198421
2  ANA3  7022496  set1H13  0.275650  0.582537
3  ANA3  7022496  set1H15  0.222707  0.280823
4  ANA3  7022496  set1H16  0.236262  0.455999

In [18]:
for col in mvp_fitness.columns:
    print(col)

print("Number of fitnesses:", len(fitness))
print("Number of mvp fitnesses:", len(mvp_fitness))

orgId
locusId
expName
fit
t
Number of fitnesses: 27410721
Number of mvp fitnesses: 8688562

***

In [19]:
media_exp = pd.read_excel("data/media_composition.xlsx", sheet_name=2)
media_exp.head()

,orgId,organism,name,Group,short,Media,Condition_1,Concentration_1,Units_1,Temperature,...,Aerobic_v_Anaerobic,Shaking,Growth.Method,has_exact_replicate,has_similar_replicate,Organism_reference,Experiment_source_dataset,Experiment_source_url,Media_source_dataset,Media_source_url
0,acidovorax_3H11,Acidovorax sp. GW101-3H11,set1IT049,stress,Nickel (II) chloride 0.6 mM,LB,Nickel (II) chloride hexahydrate,0.60,mM,25,...,Aerobic,orbital,48 well microplate; Tecan Infinite F200,True,True,this study,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...
1,acidovorax_3H11,Acidovorax sp. GW101-3H11,set1IT050,stress,Cobalt chloride 0.16 mM,LB,Cobalt chloride hexahydrate,0.16,mM,25,...,Aerobic,orbital,48 well microplate; Tecan Infinite F200,False,True,this study,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...
2,acidovorax_3H11,Acidovorax sp. GW101-3H11,set1IT051,stress,Cobalt chloride 0.32 mM,LB,Cobalt chloride hexahydrate,0.32,mM,25,...,Aerobic,orbital,48 well microplate; Tecan Infinite F200,True,True,this study,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...
3,acidovorax_3H11,Acidovorax sp. GW101-3H11,set1IT052,stress,copper (II) chloride 1 mM,LB,copper (II) chloride dihydrate,1.00,mM,25,...,Aerobic,orbital,48 well microplate; Tecan Infinite F200,True,True,this study,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...
4,acidovorax_3H11,Acidovorax sp. GW101-3H11,set1IT053,stress,sodium fluoride 25 mM,LB,sodium fluoride,25.00,mM,25,...,Aerobic,orbital,48 well microplate; Tecan Infinite F200,False,True,this study,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...

In [20]:
media_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4870 entries, 0 to 4869
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   orgId                      4870 non-null   object
 1   organism                   4870 non-null   object
 2   name                       4870 non-null   object
 3   Group                      4870 non-null   object
 4   short                      4870 non-null   object
 5   Media                      4870 non-null   object
 6   Condition_1                4369 non-null   object
 7   Concentration_1            4369 non-null   float64
 8   Units_1                    4369 non-null   object
 9   Temperature                4870 non-null   int64
 10  pH                         2066 non-null   float64
 11  Aerobic_v_Anaerobic        4870 non-null   object
 12  Shaking                    4870 non-null   object
 13  Growth.Method              4870 non-null   object
 14  has_exact_replicate        4870 non-null   bool
 15  has_similar_replicate      4870 non-null   bool
 16  Organism_reference         3921 non-null   object
 17  Experiment_source_dataset  4870 non-null   object
 18  Experiment_source_url      4870 non-null   object
 19  Media_source_dataset       4870 non-null   object
 20  Media_source_url           4870 non-null   object
dtypes: bool(2), float64(2), int64(1), object(16)
memory usage: 732.5+ KB

In [21]:
media = pd.read_excel("data/media_composition.xlsx", sheet_name=1)
media.head()

,Media,Component,Concentration,Units,Media_description,Minimal,Source_dataset,Source_url
0,ALP_defined_noC,Ammonium chloride,0.25,g/L,Defined media for Dechlorosoma suillum PS minu...,1.0,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...
1,ALP_defined_noC,Potassium Chloride,0.10,g/L,Defined media for Dechlorosoma suillum PS minu...,1.0,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...
2,ALP_defined_noC,Potassium phosphate dibasic,0.97,g/L,Defined media for Dechlorosoma suillum PS minu...,1.0,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...
3,ALP_defined_noC,Sodium phosphate monobasic monohydrate,0.49,g/L,Defined media for Dechlorosoma suillum PS minu...,1.0,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...
4,ALP_defined_noC,Wolfe's mineral mix,1.00,X,Defined media for Dechlorosoma suillum PS minu...,1.0,Price et al. bigfit Supplementary_Tables_final...,https://genomics.lbl.gov/supplemental/bigfit/S...